version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: hightechx_frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - lsof
        - '-t'
        - '-i:3000'
      timeout: 10s
      retries: 5
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: hightechx_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=hightechx12345
      - DB_HOST=hightechx_db
      - DB_NAME=HIGHTECHX_DATABASE
      - DB_PORT=3306
    healthcheck:
      test:
        - CMD
        - lsof
        - '-t'
        - '-i:3001'
      timeout: 10s
      retries: 5
    ports:
      - '3001:3001'
    restart: unless-stopped
  db:
    image: 'mysql:8.0.30'
    container_name: hightechx_db
    ports:
      - '3002:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=hightechx12345
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
